name: TownyWars
main: code.MedievalLords.townywars.TownyWars
authors: [crehop, Young_Explicit]
version: 0.1
description: A plugin made by some Programming Bat
commands:
  raid:
    description: Check Command